### ISSUE TITLE
Paclet could have Loading -> Automatic?

### ISSUE THREAD

**Issue by arnoudbuzing** [WolframResearch/codeparser#1]
If you add Loading -> Automatic to the PacletInfo file, you would not need to call Needs["CodeParser`"] every time.

Maybe this can be added?

**Comment by szhorvat** [comment]
I would strongly vote against this, not just for this package, but for almost any package.

There are already too many symbols exposed in WL by default. Packages should stay out of my way and expose their symbols only when I explicitly request it.

To be clear, *adding support* for `Automatic` loading (which it does not currently have) would be a nice addition. Then people who prefer this could set it. But making `Automatic` the default would be irritating for many of us.

**Comment by arnoudbuzing** [comment]
Hm, ok ...  I seem to be outnumbered here. I will withdrawn the suggestion.
