### ISSUE TITLE
Suggestion: Support code parsing of byte arrays

### ISSUE THREAD

**Issue by arnoudbuzing** [WolframResearch/codeparser#18]
E.g. this could be made to work:

```
ba=StringToByteArray["1+1"];
CodeParse[ba]
```

by first converting the byte array to a UTF8 string.

**Comment by bostick** [comment]
This is already on the list of things to do. It will be possible to pass a byte array directly to the parser, no conversion needed.

**Comment by bostick** [comment]
Probably will not implement. Here are a few reasons:

It has been suggested internally to deprecate `ByteArray`

There is not proper WSTP support for reading from a `ByteArray`.

Both of these do work:
`CodeParse[ByteArrayToString[ba]]`
`CodeParse[Normal[ba]]`
