### ISSUE TITLE
Reason for making"Unexpected Closer" to be always in the top-level?

### ISSUE THREAD

**Issue by kenkangxgwe** [WolframResearch/codeparser#21]
I know the behavior of "Unexpected Closer" has been decided to be always on top-level for a long time, but I am still curious about the reason, since `f[(]` and `f[)]` look alike while they are parsed into completely different AST structures.

**Comment by bostick** [comment]
This is not so much an "issue", but I will answer it here.

Even though there is only 1 character different, `f[(]` and `f[)]` are very dissimilar!

In the parser, there is a choice to either return the mismatched bracket immediately when it is encountered or to allow it to bubble-up the stack in hopes that it will find its mate.

There are pros and cons to both approaches.

Right now, the arbitrary choice is hard-coded to always bubble the mismatched bracket up the stack.

In case 1, when `]` is encountered, there are 2 groups on the stack in the middle of being parsed. The `]` bubbles up the stack, finds its mate, and successfully creates a normal GroupNode. This is the outcome that people expect.

In case 2, when `)`, there is 1 group on the stack in the middle of being parsed. The ')' bubbles up the stack, hits top-level and creates an `UnexpectedCloser` node. This also causes the `[` to create a `GroupMissingCloserNode`. The `]` is then treated as an `UnexpectedCloser`. This outcome is surprising to people.

The reverse choice could be made, to immediately eat any mismatched brackets. Then case 1 would create `GroupMissingCloserNode`, `GroupMissingCloserNode`, `UnexpectedCloser` and that would be surprising to people. And case 2 would create a normal `GroupNode` and that is what people would expect.

Obviously, it would be best in both cases to select the choice that people would expect. But it is not simple to know how to make that choice. The parser is recursive descent; the state of the parser is encoded on the stack. There is not a "state" to query whether there are certain groups currently being parsed. But perhaps there could be in the future!

I do currently keep track of the single current group being parsed. Maybe I could have a bitfield to store whether each of the different types of groups is currently being parsed. That way at least, simple cases like your example would be able to do the expected thing in both cases.

I try to keep the stack frames as small as possible, so I will have to be careful if I add more info like that.

And of course cases where there are multiple levels of the same bracket would still return unexpected things.
