### ISSUE TITLE
Version 1.1 gives wrong Source information with tab indentation

### ISSUE THREAD

**Issue by kenkangxgwe** [WolframResearch/codeparser#23]
Noticed a new option `"TabWidth" -> 4` added to `CodeParse` in version 1.1, which makes all node column offset by a multiple of 3 (4-1) if the code is indented with tabs. Considering this as a requirement from the CodeFormatter paclet,  we should let the CodeFormat pass the option instead of changing the default value of CodeParser.

**Comment by bostick** [comment]
I have changed the default to be `"TabWidth" -> 1`.

I think this makes more sense as a default.
