### ISSUE TITLE
Why do Slot and MessageName remove the Source of their children

### ISSUE THREAD

**Issue by kenkangxgwe** [WolframResearch/codeparser#5]
As the following lines indicate, the message name and slot number/string are removed as a result of `abstractSymbolString`. Is there any reason that we need to remove their `Source`s? 
https://github.com/WolframResearch/codeparser/blob/5638fb6f5bf10604f7511863f6b02c9421fa6e6f/CodeParser/Kernel/Abstract.wl#L1718
https://github.com/WolframResearch/codeparser/blob/5638fb6f5bf10604f7511863f6b02c9421fa6e6f/CodeParser/Kernel/Abstract.wl#L113

**Comment by bostick** [comment]
I will fix these up. Thanks!

**Comment by bostick** [comment]
This is addressed in this commit:
https://github.com/WolframResearch/codeparser/commit/ab88a91a60ca8bbf70ce5175eba4020b74a790bc
