### ISSUE TITLE
CodeParse // Options ... Why is "SourceConvention" a string option

### ISSUE THREAD

**Issue by arnoudbuzing** [WolframResearch/codeparser#9]
"SourceConvention" is a string option.
But ContainerNode is a symbol.

Why do they differ in type?

```
CodeParse // Options

 {CharacterEncoding -> "UTF8", "SourceConvention" -> "LineColumn", 
 ContainerNode -> Automatic}
```

**Comment by bostick** [comment]
@szhorvat no worries!

`"SourceConvention"` is a string because I didn't know if the final name was decided yet. It is pseudo-experimental, and I don't like introducing a symbol that isn't considered fully baked yet.

It's probably fine to create a `SourceConvention` symbol now.

**Comment by bostick** [comment]
I have made the `SourceConvention` option a symbol now.
